// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nested/transaction.proto

package nested // import "github.com/orbs-network/go-serialization-comparison/protobuf/nested"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressScheme int32

const (
	AddressScheme_RESERVED_SCHEME AddressScheme = 0
	AddressScheme_SCHEME01        AddressScheme = 1
	AddressScheme_FUTURE_SCHEME   AddressScheme = 255
)

var AddressScheme_name = map[int32]string{
	0:   "RESERVED_SCHEME",
	1:   "SCHEME01",
	255: "FUTURE_SCHEME",
}
var AddressScheme_value = map[string]int32{
	"RESERVED_SCHEME": 0,
	"SCHEME01":        1,
	"FUTURE_SCHEME":   255,
}

func (x AddressScheme) String() string {
	return proto.EnumName(AddressScheme_name, int32(x))
}
func (AddressScheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{0}
}

type NetworkType int32

const (
	NetworkType_RESERVED_NETWORK NetworkType = 0
	NetworkType_MAIN_NET         NetworkType = 77
	NetworkType_TEST_NET         NetworkType = 84
	NetworkType_FUTURE_NETWORK   NetworkType = 255
)

var NetworkType_name = map[int32]string{
	0:   "RESERVED_NETWORK",
	77:  "MAIN_NET",
	84:  "TEST_NET",
	255: "FUTURE_NETWORK",
}
var NetworkType_value = map[string]int32{
	"RESERVED_NETWORK": 0,
	"MAIN_NET":         77,
	"TEST_NET":         84,
	"FUTURE_NETWORK":   255,
}

func (x NetworkType) String() string {
	return proto.EnumName(NetworkType_name, int32(x))
}
func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{1}
}

type Transaction struct {
	DataBytes            []byte   `protobuf:"bytes,1,opt,name=data_bytes,json=dataBytes,proto3" json:"data_bytes,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetDataBytes() []byte {
	if m != nil {
		return m.DataBytes
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TransactionData struct {
	Header               *TransactionHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PayloadBytes         []byte             `protobuf:"bytes,2,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionData) Reset()         { *m = TransactionData{} }
func (m *TransactionData) String() string { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()    {}
func (*TransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{1}
}
func (m *TransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionData.Unmarshal(m, b)
}
func (m *TransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionData.Marshal(b, m, deterministic)
}
func (dst *TransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionData.Merge(dst, src)
}
func (m *TransactionData) XXX_Size() int {
	return xxx_messageInfo_TransactionData.Size(m)
}
func (m *TransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionData proto.InternalMessageInfo

func (m *TransactionData) GetHeader() *TransactionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TransactionData) GetPayloadBytes() []byte {
	if m != nil {
		return m.PayloadBytes
	}
	return nil
}

type TransactionHeader struct {
	ProtocolVersion      uint32   `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	VirtualChain         uint64   `protobuf:"varint,2,opt,name=virtual_chain,json=virtualChain" json:"virtual_chain,omitempty"`
	SenderBytes          []byte   `protobuf:"bytes,3,opt,name=sender_bytes,json=senderBytes,proto3" json:"sender_bytes,omitempty"`
	TimeStamp            int64    `protobuf:"varint,4,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHeader) Reset()         { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()    {}
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{2}
}
func (m *TransactionHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHeader.Unmarshal(m, b)
}
func (m *TransactionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHeader.Marshal(b, m, deterministic)
}
func (dst *TransactionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHeader.Merge(dst, src)
}
func (m *TransactionHeader) XXX_Size() int {
	return xxx_messageInfo_TransactionHeader.Size(m)
}
func (m *TransactionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHeader proto.InternalMessageInfo

func (m *TransactionHeader) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *TransactionHeader) GetVirtualChain() uint64 {
	if m != nil {
		return m.VirtualChain
	}
	return 0
}

func (m *TransactionHeader) GetSenderBytes() []byte {
	if m != nil {
		return m.SenderBytes
	}
	return nil
}

func (m *TransactionHeader) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type TransactionSender struct {
	AddressScheme        AddressScheme `protobuf:"varint,1,opt,name=address_scheme,json=addressScheme,enum=nested.AddressScheme" json:"address_scheme,omitempty"`
	NetworkType          NetworkType   `protobuf:"varint,2,opt,name=network_type,json=networkType,enum=nested.NetworkType" json:"network_type,omitempty"`
	PublicKey            []byte        `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransactionSender) Reset()         { *m = TransactionSender{} }
func (m *TransactionSender) String() string { return proto.CompactTextString(m) }
func (*TransactionSender) ProtoMessage()    {}
func (*TransactionSender) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{3}
}
func (m *TransactionSender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionSender.Unmarshal(m, b)
}
func (m *TransactionSender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionSender.Marshal(b, m, deterministic)
}
func (dst *TransactionSender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionSender.Merge(dst, src)
}
func (m *TransactionSender) XXX_Size() int {
	return xxx_messageInfo_TransactionSender.Size(m)
}
func (m *TransactionSender) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionSender.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionSender proto.InternalMessageInfo

func (m *TransactionSender) GetAddressScheme() AddressScheme {
	if m != nil {
		return m.AddressScheme
	}
	return AddressScheme_RESERVED_SCHEME
}

func (m *TransactionSender) GetNetworkType() NetworkType {
	if m != nil {
		return m.NetworkType
	}
	return NetworkType_RESERVED_NETWORK
}

func (m *TransactionSender) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type TransactionPayload struct {
	ContractName         string                `protobuf:"bytes,1,opt,name=contract_name,json=contractName" json:"contract_name,omitempty"`
	MethodName           string                `protobuf:"bytes,2,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	InputArgument        []*MethodCallArgument `protobuf:"bytes,3,rep,name=input_argument,json=inputArgument" json:"input_argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TransactionPayload) Reset()         { *m = TransactionPayload{} }
func (m *TransactionPayload) String() string { return proto.CompactTextString(m) }
func (*TransactionPayload) ProtoMessage()    {}
func (*TransactionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{4}
}
func (m *TransactionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPayload.Unmarshal(m, b)
}
func (m *TransactionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPayload.Marshal(b, m, deterministic)
}
func (dst *TransactionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPayload.Merge(dst, src)
}
func (m *TransactionPayload) XXX_Size() int {
	return xxx_messageInfo_TransactionPayload.Size(m)
}
func (m *TransactionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPayload proto.InternalMessageInfo

func (m *TransactionPayload) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *TransactionPayload) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *TransactionPayload) GetInputArgument() []*MethodCallArgument {
	if m != nil {
		return m.InputArgument
	}
	return nil
}

type MethodCallArgument struct {
	// Types that are valid to be assigned to Type:
	//	*MethodCallArgument_Uint32
	//	*MethodCallArgument_Uint64
	//	*MethodCallArgument_String_
	//	*MethodCallArgument_Bytes
	Type                 isMethodCallArgument_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MethodCallArgument) Reset()         { *m = MethodCallArgument{} }
func (m *MethodCallArgument) String() string { return proto.CompactTextString(m) }
func (*MethodCallArgument) ProtoMessage()    {}
func (*MethodCallArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_d4c0db224fc51c79, []int{5}
}
func (m *MethodCallArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodCallArgument.Unmarshal(m, b)
}
func (m *MethodCallArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodCallArgument.Marshal(b, m, deterministic)
}
func (dst *MethodCallArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodCallArgument.Merge(dst, src)
}
func (m *MethodCallArgument) XXX_Size() int {
	return xxx_messageInfo_MethodCallArgument.Size(m)
}
func (m *MethodCallArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodCallArgument.DiscardUnknown(m)
}

var xxx_messageInfo_MethodCallArgument proto.InternalMessageInfo

type isMethodCallArgument_Type interface {
	isMethodCallArgument_Type()
}

type MethodCallArgument_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,1,opt,name=uint32,oneof"`
}
type MethodCallArgument_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,2,opt,name=uint64,oneof"`
}
type MethodCallArgument_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,oneof"`
}
type MethodCallArgument_Bytes struct {
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3,oneof"`
}

func (*MethodCallArgument_Uint32) isMethodCallArgument_Type()  {}
func (*MethodCallArgument_Uint64) isMethodCallArgument_Type()  {}
func (*MethodCallArgument_String_) isMethodCallArgument_Type() {}
func (*MethodCallArgument_Bytes) isMethodCallArgument_Type()   {}

func (m *MethodCallArgument) GetType() isMethodCallArgument_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MethodCallArgument) GetUint32() uint32 {
	if x, ok := m.GetType().(*MethodCallArgument_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (m *MethodCallArgument) GetUint64() uint64 {
	if x, ok := m.GetType().(*MethodCallArgument_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (m *MethodCallArgument) GetString_() string {
	if x, ok := m.GetType().(*MethodCallArgument_String_); ok {
		return x.String_
	}
	return ""
}

func (m *MethodCallArgument) GetBytes() []byte {
	if x, ok := m.GetType().(*MethodCallArgument_Bytes); ok {
		return x.Bytes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MethodCallArgument) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MethodCallArgument_OneofMarshaler, _MethodCallArgument_OneofUnmarshaler, _MethodCallArgument_OneofSizer, []interface{}{
		(*MethodCallArgument_Uint32)(nil),
		(*MethodCallArgument_Uint64)(nil),
		(*MethodCallArgument_String_)(nil),
		(*MethodCallArgument_Bytes)(nil),
	}
}

func _MethodCallArgument_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MethodCallArgument)
	// type
	switch x := m.Type.(type) {
	case *MethodCallArgument_Uint32:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Uint32))
	case *MethodCallArgument_Uint64:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Uint64))
	case *MethodCallArgument_String_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *MethodCallArgument_Bytes:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Bytes)
	case nil:
	default:
		return fmt.Errorf("MethodCallArgument.Type has unexpected type %T", x)
	}
	return nil
}

func _MethodCallArgument_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MethodCallArgument)
	switch tag {
	case 1: // type.uint32
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &MethodCallArgument_Uint32{uint32(x)}
		return true, err
	case 2: // type.uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &MethodCallArgument_Uint64{x}
		return true, err
	case 3: // type.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &MethodCallArgument_String_{x}
		return true, err
	case 4: // type.bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Type = &MethodCallArgument_Bytes{x}
		return true, err
	default:
		return false, nil
	}
}

func _MethodCallArgument_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MethodCallArgument)
	// type
	switch x := m.Type.(type) {
	case *MethodCallArgument_Uint32:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Uint32))
	case *MethodCallArgument_Uint64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Uint64))
	case *MethodCallArgument_String_:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *MethodCallArgument_Bytes:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Bytes)))
		n += len(x.Bytes)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Transaction)(nil), "nested.Transaction")
	proto.RegisterType((*TransactionData)(nil), "nested.TransactionData")
	proto.RegisterType((*TransactionHeader)(nil), "nested.TransactionHeader")
	proto.RegisterType((*TransactionSender)(nil), "nested.TransactionSender")
	proto.RegisterType((*TransactionPayload)(nil), "nested.TransactionPayload")
	proto.RegisterType((*MethodCallArgument)(nil), "nested.MethodCallArgument")
	proto.RegisterEnum("nested.AddressScheme", AddressScheme_name, AddressScheme_value)
	proto.RegisterEnum("nested.NetworkType", NetworkType_name, NetworkType_value)
}

func init() {
	proto.RegisterFile("nested/transaction.proto", fileDescriptor_transaction_d4c0db224fc51c79)
}

var fileDescriptor_transaction_d4c0db224fc51c79 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xdf, 0x4f, 0xdb, 0x3a,
	0x14, 0x26, 0x94, 0x5b, 0xdd, 0x9e, 0xa6, 0xa5, 0xd7, 0xdc, 0x7b, 0xd5, 0x4d, 0x43, 0x63, 0xdd,
	0x0b, 0x43, 0xa2, 0x1d, 0x05, 0xf1, 0xb4, 0x97, 0x52, 0x82, 0xba, 0xa1, 0x76, 0x93, 0x1b, 0x98,
	0xb4, 0x97, 0xc8, 0x4d, 0xbc, 0xd6, 0xa2, 0xb1, 0x23, 0xdb, 0x61, 0xea, 0x1e, 0xf7, 0x7f, 0xec,
	0x71, 0xd2, 0xfe, 0x4b, 0x26, 0xdb, 0x09, 0x14, 0xf1, 0xc6, 0xf7, 0xc3, 0xe7, 0x7c, 0x39, 0x1f,
	0x85, 0x36, 0xa7, 0x4a, 0xd3, 0xa4, 0xa7, 0x25, 0xe1, 0x8a, 0xc4, 0x9a, 0x09, 0xde, 0xcd, 0xa4,
	0xd0, 0x02, 0x55, 0x9d, 0xd2, 0xf9, 0x00, 0xf5, 0xf0, 0x41, 0x44, 0xbb, 0x00, 0x09, 0xd1, 0x24,
	0x9a, 0xad, 0x34, 0x55, 0x6d, 0x6f, 0xcf, 0xdb, 0xf7, 0x71, 0xcd, 0x30, 0x67, 0x86, 0x40, 0x2f,
	0xa0, 0xa6, 0xd8, 0x9c, 0x13, 0x9d, 0x4b, 0xda, 0xde, 0x74, 0xea, 0x3d, 0xd1, 0x61, 0xb0, 0xbd,
	0x36, 0xeb, 0x9c, 0x68, 0x82, 0x8e, 0xa0, 0xba, 0xa0, 0x24, 0xa1, 0xd2, 0xce, 0xaa, 0xf7, 0x9f,
	0x75, 0xdd, 0xde, 0xee, 0x9a, 0x71, 0x64, 0x0d, 0xb8, 0x30, 0xa2, 0xd7, 0xd0, 0xc8, 0xc8, 0x6a,
	0x29, 0x48, 0x52, 0xa4, 0x70, 0x7b, 0xfc, 0x82, 0xb4, 0x41, 0x3a, 0xbf, 0x3c, 0xf8, 0xe7, 0xc9,
	0x08, 0xf4, 0x06, 0x5a, 0xf6, 0xeb, 0x62, 0xb1, 0x8c, 0x6e, 0xa9, 0x54, 0x4c, 0x70, 0xbb, 0xb7,
	0x81, 0xb7, 0x4b, 0xfe, 0xda, 0xd1, 0x66, 0xcb, 0x2d, 0x93, 0x3a, 0x27, 0xcb, 0x28, 0x5e, 0x10,
	0xc6, 0xed, 0x96, 0x2d, 0xec, 0x17, 0xe4, 0xd0, 0x70, 0xe8, 0x15, 0xf8, 0x8a, 0xf2, 0x84, 0xca,
	0x22, 0x49, 0xc5, 0x26, 0xa9, 0x3b, 0xce, 0x5d, 0x64, 0x17, 0x40, 0xb3, 0x94, 0x46, 0x4a, 0x93,
	0x34, 0x6b, 0x6f, 0xed, 0x79, 0xfb, 0x15, 0x5c, 0x33, 0xcc, 0xd4, 0x10, 0x9d, 0xdf, 0x8f, 0x73,
	0x4e, 0xed, 0x4b, 0xf4, 0x0e, 0x9a, 0x24, 0x49, 0x24, 0x55, 0x2a, 0x52, 0xf1, 0x82, 0xa6, 0xd4,
	0xa6, 0x6c, 0xf6, 0xff, 0x2b, 0xaf, 0x33, 0x70, 0xea, 0xd4, 0x8a, 0xb8, 0x41, 0xd6, 0x21, 0x3a,
	0x05, 0x9f, 0x53, 0xfd, 0x4d, 0xc8, 0x9b, 0x48, 0xaf, 0x32, 0xd7, 0x43, 0xb3, 0xbf, 0x53, 0xbe,
	0x9d, 0x38, 0x2d, 0x5c, 0x65, 0x14, 0xd7, 0xf9, 0x03, 0x30, 0x51, 0xb3, 0x7c, 0xb6, 0x64, 0x71,
	0x74, 0x43, 0x57, 0xc5, 0xb7, 0xd4, 0x1c, 0x73, 0x49, 0x57, 0x9d, 0x9f, 0x1e, 0xa0, 0xb5, 0xa8,
	0x9f, 0xdc, 0xb9, 0xcd, 0xa1, 0x62, 0xc1, 0xb5, 0x24, 0xb1, 0x8e, 0x38, 0x29, 0xa2, 0xd6, 0xb0,
	0x5f, 0x92, 0x13, 0x92, 0x52, 0xf4, 0x12, 0xea, 0x29, 0xd5, 0x0b, 0x91, 0x38, 0xcb, 0xa6, 0xb5,
	0x80, 0xa3, 0xac, 0x61, 0x00, 0x4d, 0xc6, 0xb3, 0x5c, 0x47, 0x44, 0xce, 0xf3, 0x94, 0x72, 0xdd,
	0xae, 0xec, 0x55, 0xf6, 0xeb, 0xfd, 0xe7, 0x65, 0xea, 0xb1, 0xf5, 0x0e, 0xc9, 0x72, 0x39, 0x28,
	0x1c, 0xb8, 0x61, 0x5f, 0x94, 0xb0, 0xf3, 0xc3, 0x03, 0xf4, 0xd4, 0x85, 0xda, 0x50, 0xcd, 0x19,
	0xd7, 0xc7, 0x7d, 0xd7, 0xf4, 0x68, 0x03, 0x17, 0xb8, 0x54, 0x4e, 0x4f, 0x5c, 0xb7, 0xa5, 0x72,
	0x7a, 0x62, 0x14, 0xa5, 0x25, 0xe3, 0x73, 0x7b, 0x85, 0x9a, 0x51, 0x1c, 0x46, 0xff, 0xc3, 0x5f,
	0xae, 0x6a, 0xd3, 0xa4, 0x3f, 0xda, 0xc0, 0x0e, 0x9e, 0x55, 0x61, 0xcb, 0xdc, 0xfa, 0xe0, 0x02,
	0x1a, 0x8f, 0xba, 0x41, 0x3b, 0xb0, 0x8d, 0x83, 0x69, 0x80, 0xaf, 0x83, 0xf3, 0x68, 0x3a, 0x1c,
	0x05, 0xe3, 0xa0, 0xb5, 0x81, 0x7c, 0xf8, 0xdb, 0xfd, 0xfd, 0xf6, 0xa8, 0xe5, 0x21, 0x04, 0x8d,
	0x8b, 0xab, 0xf0, 0x0a, 0x07, 0xa5, 0xe1, 0xce, 0x3b, 0x08, 0xa1, 0xbe, 0xd6, 0x13, 0xfa, 0x17,
	0x5a, 0xf7, 0x53, 0x26, 0x41, 0xf8, 0xf9, 0x23, 0xbe, 0x74, 0x63, 0xc6, 0x83, 0xf7, 0x13, 0xc3,
	0xb4, 0xc6, 0x06, 0x85, 0xc1, 0x34, 0xb4, 0x28, 0x44, 0x3b, 0xd0, 0x2c, 0x86, 0x96, 0xfe, 0x3b,
	0xef, 0x2c, 0xf8, 0x32, 0x9c, 0x33, 0xbd, 0xc8, 0x67, 0xdd, 0x58, 0xa4, 0x3d, 0x21, 0x67, 0xea,
	0xb0, 0xf8, 0x07, 0xe8, 0xcd, 0xc5, 0xa1, 0xa2, 0x92, 0x91, 0x25, 0xfb, 0x4e, 0x4c, 0xbd, 0x87,
	0xb1, 0x48, 0x33, 0x22, 0x99, 0x12, 0xbc, 0x67, 0x7f, 0x1b, 0xb3, 0xfc, 0x6b, 0xcf, 0x75, 0x31,
	0xab, 0x5a, 0xe2, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x16, 0x6a, 0x20, 0x3e, 0x04,
	0x00, 0x00,
}
