// automatically generated by the FlatBuffers compiler, do not modify

package nested

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransactionData struct {
	_tab flatbuffers.Table
}

func GetRootAsTransactionData(buf []byte, offset flatbuffers.UOffsetT) *TransactionData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransactionData{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TransactionData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransactionData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransactionData) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TransactionDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransactionDataAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func TransactionDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
